// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpmvjrjtyxivfzpaveju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwbXZqcmp0eXhpdmZ6cGF2ZWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NDAwODcsImV4cCI6MjA1MzQxNjA4N30.MuT0D-TzjIDuIMgyajcylw_8KD4w-FKX4J6MS2DPwNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);